<?php
/**
 * NOTICE OF LICENSE
 *
 * Subject to the terms, conditions and limitations of this EULA,
 * Company hereby grants you a limited, nonexclusive, nontransferable,
 * non-assignable license, without rights to sublicense, to install or have installed,
 * display and use the Software (in object code only) only on the computers
 * to which the Software is downloaded.  The terms and conditions of this EULA
 * will govern any upgrades, updates, patches, hotfixes and/or
 * additional versions of the Software provided by Company, at Company’s sole
 * discretion, that replace and/or supplement the original Software (collectively, “Update”),
 * unless such Update is accompanied by or references a separate license
 * agreement in which case the terms and conditions of that agreement will
 * govern.  If this EULA governs your use of an Update, such Update shall be
 * considered Software for purposes of this EULA. Unless earlier terminated
 * as provided herein, the term of each individual license granted under this
 * EULA begins on the date of acceptance of this EULA and shall terminate only
 * as otherwise set forth herein.Each party recognizes that
 * Company grants no licenses except for the license expressly set forth.
 *
 * @category    Invodo
 * @package     Invodo_Video
 * @copyright   Copyright (c) 2013 INVODO (http://www.invodo.com/)
 * @license     http://opensource.org/licenses/OSL-3.0 Open Source Software
 */
?>
<?php
/** @var Invodo_Video_Block_Adminhtml_Widget_Renderer_Overlayactionsource $this */
/** @var Varien_Data_Form_Element_Abstract $_element */
$_element = $this->getElement();
$_note    = $_element->getNote();
$_trId    = $_element->getHtmlContainerId();
$_class   = $_element->getFieldsetHtmlClass();
$_height  = $_element->getEscapedValue() ? $_element->getEscapedValue() : Invodo_Video_Helper_Data::DEFAULT_VIDEO_HEIGHT;
$_mediaUrl = Mage::getUrl('adminhtml/cms_wysiwyg_images', array('target_element_id' => trim($_element->getHtmlId()), 'invodo_video' => true));
?>
<?php if (!$_element->getNoDisplay()): ?>
    <tr<?php if($_trId): ?> id="<?php echo $_trId ?>"<?php endif; ?>>
        <td class="label<?php echo $_class ? " {$_class}-label" : ''?>"><?php echo trim($_element->getLabelHtml()) ?></td>
        <td class="<?php echo $_element->hasValueClass() ? $_element->getValueClass() : 'value' ?><?php echo $_class ? " {$_class}-value" : ''?>">
            <input onclick="javascript: MediabrowserUtility.openDialog('<?php echo $_mediaUrl; ?>');" name="<?php echo trim($_element->getName()) ?>" type="text" id="<?php echo trim($_element->getHtmlId()) ?>" value="<?php echo trim($_element->getEscapedValue()) ?>" style="width: 260px;" class="required-entry" disabled readonly />
            <img src="<?php echo $this->getSkinUrl('images/application_view_tile.gif') ?>" onclick="javascript: MediabrowserUtility.openDialog('<?php echo $_mediaUrl; ?>');" style="cursor: pointer; vertical-align: middle;" />
            <?php if ($_note): ?>
                <p class="note<?php echo $_class ? " {$_class}-note" : ''?>" id="note_<?php echo $_element->getId()?>"><span><?php echo $_note ?></span></p>
            <?php endif ?>
        </td>
    </tr>
<?php endif; ?>