<?php
/**
 * NOTICE OF LICENSE
 *
 * Subject to the terms, conditions and limitations of this EULA,
 * Company hereby grants you a limited, nonexclusive, nontransferable,
 * non-assignable license, without rights to sublicense, to install or have installed,
 * display and use the Software (in object code only) only on the computers
 * to which the Software is downloaded.  The terms and conditions of this EULA
 * will govern any upgrades, updates, patches, hotfixes and/or
 * additional versions of the Software provided by Company, at Company’s sole
 * discretion, that replace and/or supplement the original Software (collectively, “Update”),
 * unless such Update is accompanied by or references a separate license
 * agreement in which case the terms and conditions of that agreement will
 * govern.  If this EULA governs your use of an Update, such Update shall be
 * considered Software for purposes of this EULA. Unless earlier terminated
 * as provided herein, the term of each individual license granted under this
 * EULA begins on the date of acceptance of this EULA and shall terminate only
 * as otherwise set forth herein.Each party recognizes that
 * Company grants no licenses except for the license expressly set forth.
 *
 * @category    Invodo
 * @package     Invodo_Video
 * @copyright   Copyright (c) 2013 INVODO (http://www.invodo.com/)
 * @license     http://opensource.org/licenses/OSL-3.0 Open Source Software
 */
?>
<?php
/** @var Varien_Data_Form_Element_Abstract $_element */
/** @var Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset_Element $this */
$_element = $this->getElement();
$_note    = $_element->getNote();
$_trId    = $_element->getHtmlContainerId();
$_class   = $_element->getFieldsetHtmlClass();
?>
<?php if (!$_element->getNoDisplay()): ?>
    <tr<?php if($_trId): ?> id="<?php echo $_trId ?>"<?php endif; ?>>
        <?php if ($_element->getType()=='hidden'): ?>
            <td colspan="2" class="hidden"><?php echo trim($_element->getElementHtml()) ?></td>
        <?php else: ?>
            <td class="label<?php echo $_class ? " {$_class}-label" : ''?>"><label for="<?php echo $this->escapeHtml($_element->getHtmlId()); ?>"><?php echo $this->escapeHtml($_element->getLabel()); ?><span class="required">*</span></label><a href="https://my.invodo.com/home/shelby.html" target="_blank"><?php echo $this->__('Lookup in MyInvodo'); ?></a></td>
            <td class="<?php echo $_element->hasValueClass() ? $_element->getValueClass() : 'value' ?><?php echo $_class ? " {$_class}-value" : ''?>">
                <?php echo trim($_element->getElementHtml()) ?>
                <?php if ($_note): ?>
                    <p class="note<?php echo $_class ? " {$_class}-note" : ''?>" id="note_<?php echo $_element->getId()?>"><span><?php echo $_note ?></span></p>
                <?php endif ?>
            </td>
        <?php endif; ?>
    </tr>
<?php endif; ?>
